version: '3.4'

services:
  medcatweb:
    build:
      context: ./webapp
      args:
        REINSTALL_CORE_FROM_LOCAL: "true"
    command: >
      bash -c "/etc/init.d/cron start &&
               python /webapp/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../medcat-v2/tests/resources:/webapp/models
      # below is use to install push-time medcat library
      - ../medcat-v2:/webapp/medcat-v2
    ports:
      - "8000:8000"
    env_file:
      - ./envs/env_medmen_test
    tty: true
