name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [
          ./notebooks/introductory/migration/*.ipynb,
          # NOTE: run these together / in sequence
          ./notebooks/introductory/basic/1*.ipynb ./notebooks/introductory/basic/2*.ipynb ./notebooks/introductory/basic/3*.ipynb ./notebooks/introductory/meta/*.ipynb,
          ./notebooks/advanced/*.ipynb,
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Install IPython kernel
        run: |
          python -m ipykernel install --name smoketests --user
      - name: Smoke test tutorial
        run: |
          pytest --collect-only --nbmake ${{ matrix.part }}
          pytest --nbmake -n=auto --nbmake-kernel=smoketests --nbmake-timeout=1800 ${{ matrix.part }}