name: medcat-v2-tutorials - Test

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'medcat-v2/**'
      - 'medcat-v2-tutorials/**'
      - '.github/workflows/medcat-v2**'
      - '.github/workflows/medcat-v2-tutorials**'
defaults:
  run:
    working-directory: ./medcat-v2-tutorials

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      medcat-branch: ${{ steps.resolve.outputs.branch }}
    steps:
      - uses: actions/checkout@v4
      - name: Resolve medcat branch
        id: resolve
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}" >> $GITHUB_OUTPUT

  basic-and-meta:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -U pip
          # install medcat based on changes in the PR
          pip install --no-deps "git+https://github.com/CogStack/cogstack-nlp@${{ needs.preflight.outputs.medcat-branch }}#subdirectory=medcat-v2"
          pip install -r requirements.txt

      - name: Update install targets in notebooks
        run: |
          python .ci/patch_notebooks.py ${{ needs.preflight.outputs.medcat-branch }}

      - name: Install IPython kernel
        run: |
          python -m ipykernel install --name smoketests --user
      - name: Smoke test tutorial
        # NOTE: these need to be run separately so that order is guaranteed
        run: |
          pytest --collect-only --nbmake ./notebooks/introductory/basic/1*.ipynb
          pytest --collect-only --nbmake ./notebooks/introductory/basic/2*.ipynb
          pytest --collect-only --nbmake ./notebooks/introductory/basic/3*.ipynb
          pytest --collect-only --nbmake ./notebooks/introductory/meta/*.ipynb
          pytest --nbmake -n=auto --nbmake-kernel=smoketests --nbmake-timeout=1800 ./notebooks/introductory/basic/1*.ipynb
          pytest --nbmake -n=auto --nbmake-kernel=smoketests --nbmake-timeout=1800 ./notebooks/introductory/basic/2*.ipynb
          pytest --nbmake -n=auto --nbmake-kernel=smoketests --nbmake-timeout=1800 ./notebooks/introductory/basic/3*.ipynb
          pytest --nbmake -n=auto --nbmake-kernel=smoketests --nbmake-timeout=1800 ./notebooks/introductory/meta/*.ipynb
          pytest --nbmake -n=auto --nbmake-kernel=smoketests --nbmake-timeout=1800 ./notebooks/introductory/custom/*.ipynb

  migrate-and-advanved:
    needs: preflight
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [
          ./notebooks/introductory/migration/*.ipynb,
          ./notebooks/introductory/relcat/*.ipynb,
          ./notebooks/advanced/*.ipynb,
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -U pip
          # install medcat based on changes in the PR
          pip install --no-deps "git+https://github.com/CogStack/cogstack-nlp@${{ needs.preflight.outputs.medcat-branch }}#subdirectory=medcat-v2"
          pip install -r requirements.txt

      - name: Update install targets in notebooks
        run: |
          python .ci/patch_notebooks.py ${{ needs.preflight.outputs.medcat-branch }}

      - name: Install IPython kernel
        run: |
          python -m ipykernel install --name smoketests --user
      - name: Smoke test tutorial
        run: |
          pytest --collect-only --nbmake ${{ matrix.part }}
          pytest --nbmake -n=auto --nbmake-kernel=smoketests --nbmake-timeout=1800 ${{ matrix.part }}
