name: medcat-v2 - Build Python Package

on:
  push:
    tags:
      - "medcat/v*"

permissions:
  contents: write

defaults:
  run:
    working-directory: ./medcat-v2

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout release branch
        run: |
          # Fetch all branches to ensure we can access the one we need
          git fetch --all

          # Get the tag without the 'v' and strip the patch version
          VERSION_TAG="${GITHUB_REF#refs/tags/}"
          # NOTE: branch name is in line with version tag, except for the patch version
          BRANCH_NAME="${VERSION_TAG%.*}"  # This removes the patch version (everything after the second dot)

          # Check out the corresponding release branch (e.g., medcat-v0.1)
          git checkout $BRANCH_NAME

          # Ensure the branch is up-to-date with the remote
          git pull origin $BRANCH_NAME

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          # softprops/action-gh-release v2 doesnt support the working-directory field, so put the path in files
          files: |
            medcat-v2/dist/*

      # Uncomment and modify this for PyPI publishing in the future
      # - name: Publish to PyPI
      #   if: false # Set to `true` or remove when ready
      #   env:
      #     PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      #   run: |
      #     pip install --upgrade twine
      #     twine upload dist/*
